--liquibase formatted sql

-- changeset dev:1.0-create-person-table-oracle
--precondition-dbms type:oracle
--precondition-sql-check expectedResult:0
SELECT COUNT(*) FROM user_tables WHERE table_name = 'PERSON';
CREATE TABLE person (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255)
);
-- Insert sample data
INSERT INTO person (name) VALUES ('Alice');
INSERT INTO person (name) VALUES ('Bob');
-- Create index
CREATE INDEX idx_person_name ON person(name);
-- Add unique constraint
ALTER TABLE person ADD CONSTRAINT uq_person_name UNIQUE (name);

-- changeset dev:1.0-create-person-trigger-oracle
--precondition-dbms type:oracle
--comment: Include PL/SQL trigger for Oracle
--sqlFile path:db/changelog/oracle/person_name_default_trg.sql relativeToChangelogFile:true

-- changeset dev:1.0-create-person-table-clickhouse
--precondition-dbms type:clickhouse
--precondition-sql-check expectedResult:0
SELECT count() FROM system.tables WHERE name = 'person';
CREATE TABLE person (
    id UInt32,
    name String
) ENGINE = MergeTree()
ORDER BY id;
-- Create index (ClickHouse uses data skipping indexes)
ALTER TABLE person ADD INDEX idx_person_name name TYPE minmax GRANULARITY 1;
-- ClickHouse does not support unique constraints on tables.

-- changeset dev:1.0-insert-person-clickhouse
--precondition-dbms type:clickhouse
--comment: Insert sample data for ClickHouse
--sqlFile path:db/changelog/clickhouse/person_insert.sql relativeToChangelogFile:true
