openapi: 3.1.0
info:
  title: Pricing API
  version: 1.0.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
paths:
  /prices:
    get:
      operationId: listPrices
      parameters:
        - name: ccyPair
          in: query
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{6}$'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/PriceList' }
components:
  schemas:
    Quote: { $ref: './components/schemas/Quote.yaml' }
    PriceList: { $ref: './components/schemas/PriceList.yaml' }
